package plugin

// Code generated by internal/plugin/cmd/genseed. DO NOT EDIT.
//
// Встроенный allow-list: плагины, содержимое которых совпадает с пин-ом
// реестра (registry.yaml), доверены без записи в конфиге оператора. Он нужен
// для совместимости: до инверсии плагин считался доверенным по умолчанию, и без
// засева реестровые плагины стали бы untrusted, а вне Linux (где изолятора
// нет) перестали бы работать вовсе.
//
// Что это значит для пользователя: доверенность проверяется по хэшу
// содержимого, поэтому подмена файла в установленном плагине понижает
// доверие, даже если id остался прежним. Community-плагин, которого нет в
// registry.yaml, доверен не будет — для него нужна запись в
// wedra-trust.yaml.

var builtinTrusted = map[string][]string{
	"abuseipdb": {
		"sha256:3550f163bd1351a6797344def3200bc60bff28ceb2b942a707354b2a6444a166",
	},
	"altdns": {
		"sha256:b60367d5498fb8ff721892742f8ac65c94ee86661f8c20c47318127ffefa9fe1",
	},
	"arjun": {
		"sha256:87f207deb135861fec364490c7cb5be9ab26b439f9ef230f1af880581e47ea78",
	},
	"batch_email_triage": {
		"sha256:6147a5d3793947967e2c891187472d7a54dd8a5bf3e3e5cc0c80bbaf9a2d85d2",
	},
	"binwalk": {
		"sha256:37e78d7d20e5e8450412660e556aa404b5b26d72a1e702c8678ac7e74b6440dc",
	},
	"buckethacker": {
		"sha256:bbeea340e52396ca2ed207da58260d060872fd69737a4fd75a1360dbb8fbd6b2",
	},
	"censys": {
		"sha256:83562df73d8140fb41d6e00bebeb973e0bdee58cfd997b68c7b8e21667c10342",
	},
	"cloud_enum": {
		"sha256:63a8648a67fd6834356052a3d89bfc1a189b4b2265e5e52ed710931e34e2ef44",
	},
	"cloudmapper": {
		"sha256:5ace1408364083bc38f24fe89c5f5cb7fdb5d0e74a7124d50c4ef77ed1de7f51",
	},
	"commix": {
		"sha256:92b48e79aa65241b3c64d08b183370ac7280a9deb7fb23849cc4cea6e50066d7",
	},
	"corsy": {
		"sha256:eb263fbc63f660a2132f6ee0931ae2f1f581692ae61e5b004673801d97775b31",
	},
	"crtsh": {
		"sha256:fdd0ab01187e0eb6b3412c7ada11401f8584023826ecafa168eca3a42a00295a",
	},
	"csv_loader": {
		"sha256:2d11450b0829c3136dd3b1ee04cc95c28ccbf9f4d36a075ea762f6d837cb295a",
	},
	"date_parser": {
		"sha256:3c4cf503c2cceab61d828f8825bec5c04cd7b6feeb2a024fb4bf9f94ba26d153",
	},
	"degoogle": {
		"sha256:a899edc42f77775814ac4a0f54acfe3ad8cbf49d0c77156bc4bfc1b081e6d1ed",
	},
	"detect_secrets": {
		"sha256:eb6b16a7ef74f2272038376615f07686e1076c2832af7df786f7adfd0845fce5",
	},
	"dir_lister": {
		"sha256:d9a679dad037a4c5de762a4f5522229ccf7e6435813d8e038f163efb72b9949d",
	},
	"dirsearch": {
		"sha256:d0c25eef85035f85d44aa8a209ebf0dc186b8d64adbe25747f478b6fd164a3a2",
	},
	"disposable_checker": {
		"sha256:84cc805f04d72deb42db0757f2ec3e92b83dab130af52cff53cdba3f402bce49",
	},
	"dnsrecon": {
		"sha256:3e68e4b61f6a372088d08dcfb93fe6a7640493009ee12d212680f375e6e81b18",
	},
	"dnstwist": {
		"sha256:8d90ee2897cf872e3601ea785ef424427e18893eb61ee0d60b679e3cbc9befa4",
	},
	"droopescan": {
		"sha256:290fe4f136d4d806bcb5d47aba57506a6aaa5f961acc46e7a124e9b7c08efb61",
	},
	"email_triage": {
		"sha256:fabb3381b8123d587f34eb4bb04fe8ca381309e36390b8a80d93f3660e41749f",
	},
	"emailfinder": {
		"sha256:ce07da8d70389a3d38c6140eec06b4973d3b4c5b353cd2ea74fa0a0fdf269493",
	},
	"exifread": {
		"sha256:d4ef92dc6e9746d1d668a49b46dd4cc89452fa0898c352264c89ef3e13d5d3ca",
	},
	"exiftool": {
		"sha256:1fcb29114989946f61165f859f00b9aa47165f277b5d7d5d0fb69a217303103c",
	},
	"fierce": {
		"sha256:29b0f629ba416b79ecfe233b2d4edb9492ed22b564a2cdd0c5a4b2c7b2d2d97b",
	},
	"gallery_dl": {
		"sha256:023500b124e7ac376dba314dabef125344189368aa2429b3df35d5cc2eaa2d7c",
	},
	"geoiplookup": {
		"sha256:b14e787bfc18b7b738d49ea15da507ab816c115f9753786cf46bddbb1210745f",
	},
	"ghauri": {
		"sha256:eebfb429b82c10e6377ff1efa929271ea2ad85be46ed6b0373221aaec0ea95d8",
	},
	"ghunt": {
		"sha256:6fe3da44d1878a5909acc4d028f54f9c1e099ff9bd44ee754304e1dc75c97059",
	},
	"git_dumper": {
		"sha256:0acbb516bcdfdb53a5a0a9c56a42b3e16bca85c0b8a57f108842ebb07d76132e",
	},
	"gospider": {
		"sha256:4f7b79ddc7c510c18121e4b200baa84964884f81830dd3369bd7071d2e266951",
	},
	"h8mail": {
		"sha256:04704ff1a67c0525d26ff9a8407113400823dfd2d89a8b368a3524a8fcd0b2b5",
	},
	"hakrawler": {
		"sha256:3f3957b8a820b9b99512a7108f573f7f15a51f6d0376ea28b11083c5a4bcd1a2",
	},
	"holehe": {
		"sha256:b27b6bce65484831e1e4c3245f9b5a9851a4a1f29e04e9ea7644912720a8f855",
	},
	"iban_validator": {
		"sha256:e1baaf7ec196416d3eba97e3b83b97a7d9313f8ed7ad1ae8e44a1c23b40fab73",
	},
	"instaloader": {
		"sha256:2e3ebb716cc66e59e867b588dfeb759c42ba48cb95b0b4330c1c1a19bf1552a9",
	},
	"ipwhois": {
		"sha256:09e1b36946d23124c9e8fa3bd19c26d4ecbbc1087a0019da500c9357025683dc",
	},
	"joomscan": {
		"sha256:66d1a01e1d1e8acc0efaa28410910aea4512a15ea29d7e27de2fd66ea891503a",
	},
	"json_diff": {
		"sha256:7c546414dca3d9a9f8a36382026f683366a9f9e68e4ea27e6cbd2bc72a4f92c4",
	},
	"json_flatten": {
		"sha256:96d2d7ed71545820452da5f19b129f673f06c012923d610498eec004d82deadf",
	},
	"lief": {
		"sha256:c363857ddd654c01143010e95dd6b6b8a3230c29dea8b54bd5fbb5531036c4b8",
	},
	"linkfinder": {
		"sha256:4221e871b01458d947864a304b989e96263d03288a0ab57e779f417ea2792a38",
	},
	"llm_anthropic": {
		"sha256:cedfa2fcae9698d3d004b358b1efea438de0174f9a4d4006fcd96a43cacbf3e0",
	},
	"llm_gemini": {
		"sha256:bd7f1024515128c5f307092e863debbbcc3613a1fde6d4d83e883b9594a9320a",
	},
	"llm_openai": {
		"sha256:693385866e285e2cf3e06bd277deff35e742ea0fa0b310e6e699321decfbe935",
	},
	"maigret": {
		"sha256:9843ac42ae0559ad3f50f7eca46ec752a0d646996be7c60cb2b01d2325183a35",
	},
	"metafinder": {
		"sha256:266e4ab92115a7b8bab1b75edf8b4340dc911d5a14723bf02bc5bb53d2360300",
	},
	"msoffcrypto_tool": {
		"sha256:53a7ad4c06d114bae5159c418ee73e39b841d79f1bffb1e77f446f275a495ebf",
	},
	"nosqlmap": {
		"sha256:4af8531f3590815fb627a7415323c12fcb4200b81e01fd811f59378fa96a68bb",
	},
	"oletools": {
		"sha256:d8d7de6420affd0b08c31190637320e333338e92c1e35dfe0d9cbe4448558736",
	},
	"otx_pulse": {
		"sha256:00348f922dccc1f50ee587a375b13776a326ab75d9a89852006889292b339f6b",
	},
	"pefile": {
		"sha256:657ba1304110261e98c861d29c8d1d98b49b0191b884b2fb1dadaa9126a0b9ad",
	},
	"phone_check": {
		"sha256:5c60667d490ba6662dad8438f1f7e8374161c78122c9522bbd6323211b30544d",
	},
	"phone_normalizer": {
		"sha256:92d91fa9e20547390089a99c8d3c92d95326808ecdcac0e0d7f627e38123c68d",
	},
	"pocsuite3": {
		"sha256:26db1f271663270e89d0f43cc454892c98f43538ff000a27ccb757234bf5c4ff",
	},
	"prowler": {
		"sha256:12be80b0981cc51ce97cec465f030b08c3a3e6701ccab7c3d7f5b21814d6a9c6",
	},
	"pyelftools": {
		"sha256:70b223971db659f80369a9f83aba168c466399696ff2f7d0f7ed546d97cbfaa0",
	},
	"python_whois": {
		"sha256:f9e517b6fcd97b3b885093ffe9a1177e8b3adcb50ef85ef4bf7a77af7dd492f1",
	},
	"recon_ng": {
		"sha256:3402cf7c4d81200c02c633cd49de6814cf8958e25d5098a7d6bd20b403ccff1f",
	},
	"report_formatter": {
		"sha256:018973a616b432e49cf0e0c8ce4d438b87fb109c371790710a43d6d1ff17351e",
	},
	"scoutsuite": {
		"sha256:4ec007d27525309ee763ad71c7b635a8b3440e09777c18e9f7bf34f7664bc107",
	},
	"sherlock": {
		"sha256:89fc2699bc048bfdd87dedc6e145ec56ed2ccfe94f4392deeb3d880aaf6fd436",
	},
	"shodan": {
		"sha256:5e77dc0ef794a823349287012ff9399dea95310de8b0da52d75611aec5e6e72e",
	},
	"social_analyzer": {
		"sha256:d5a61b639126d2334af86eb8d2c5c4f06f8c7f54a96c5afcd7e02d313009966c",
	},
	"spiderfoot": {
		"sha256:237ee0604268daf57f92a7a3a154e3bbcbd26c823f7ea2fcaabb3ed2d8da934e",
	},
	"sqlmap": {
		"sha256:d72a5a8a267e8c8dbe5d03de7b8a0fb906380395eee36b5f53076915c4a794bf",
	},
	"sslyze": {
		"sha256:3d8643c678d70706821bfb33a23875397310d2e8529644a68b8d9d8cf583f1a4",
	},
	"sublist3r": {
		"sha256:514f6c854314a0f2ed1498880f640a0cdc9407137b3ffd2ac5b3a93ba2a3cc7d",
	},
	"syntax_mx_checker": {
		"sha256:48c1cb0adcf2d6ebe9e98e01589ba4a8f60b4a4c9fada691389e2057d6af0c59",
	},
	"text_analyzer": {
		"sha256:505eff408b9b74955dafd95af63b7b961442567603f083913718ee389ab361bb",
	},
	"text_similarity": {
		"sha256:41560804101f826684ed0be88438ca297e0d2874941de89d4b8e4080703eb205",
	},
	"the_harvester": {
		"sha256:c8e670cd18a3d9293e18baaa643bf5c851e70e5dd06591a84a8397db42c5175f",
	},
	"threatfox": {
		"sha256:347c086d713db10ac28f1dde729a2cd777c570ba85d7a7a9d81049396d6e5808",
	},
	"tplmap": {
		"sha256:47323e3bbdfb61edf7ec2201e8cc073fe9b0b1190bdb4e523e8ddd491d50a155",
	},
	"virustotal": {
		"sha256:806ea64e886132f5737b8096c497dea540173728731be7015468aa673df80bb1",
	},
	"volatility3": {
		"sha256:0b3be6f5e390f0ff81c662a164ef431ee9309f8361b31df1072490822d7a7813",
	},
	"wafw00f": {
		"sha256:66e54cf07757663e53a2e8bc6e1c0693e92b373c7527f7fdab1686ac892cbd2c",
	},
	"wapiti": {
		"sha256:bf42dc5efbaee20238028ce0c4defaad89787f7891bde0169642868af8a57568",
	},
	"webanalyze": {
		"sha256:704f237ff584cb426bfbdb6026f90bff217e87f690d4970b3084a9d04223e1b9",
	},
	"wfuzz": {
		"sha256:91534ff389ef69b0879b8412f02f93292235b4d7017a0367eb0a2e27ce80d063",
	},
	"word_freq": {
		"sha256:40a2d2ebf959818dfb6a97336236d87261e4748f18984a2b0ed48aa9485fefe5",
	},
	"xsstrike": {
		"sha256:1f071e78c325335af53f785d2e28b3ce39e4606f8f31218f8640f95df0642e68",
	},
	"you_get": {
		"sha256:15b98a4701a6544c5cbb774fcd3d9da558317d11caf4fd84de102966c3bb0822",
	},
	"yt_dlp": {
		"sha256:f88de520a315032c37d632c65832f4229a550d729c02f0d46af4250f25467fda",
	},
}
